spring:
  dubbo:
    application:
      name: manage-web
    protocol: dubbo
    registry:
      address: 117.78.9.213:2181
      protocol: zookeeper
    base-package: com.ljp.gmall
    consumer:
      check: false
      timeout: 600000

#服务信息
server:
  port: 8081

#日志级别
logging:
  level:
    root: info

